databases:
  - name: agreetojoin-db
    databaseName: agreetojoin
    plan: free
    region: singapore

services:
  - type: web
    name: agreetojoin-app
    env: node
    region: singapore
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: agreetojoin-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: REMOVE_BG_API_KEY
        sync: false
